### Get all foods
GET http://localhost:3002/api/foods


### Create new food
POST http://localhost:3000/api/foods
content-type: application/json

{
    "name": "flour",
    "brand": "generic",
    "isFood": true,
    "measures": [
        {
            "label": "grams",
            "quantity": 125,
            "calories": 455,
            "carbs": 95,
            "fat": 1.2,
            "protein": 13
        },
        {
            "label": "cup(s)",
            "quantity": 1,
            "calories": 455,
            "carbs": 95,
            "fat": 1.2,
            "protein": 13
        }
    ]
}


### Get a single food
GET http://localhost:3000/api/foods/1


### Search foods
GET http://localhost:3000/api/foods?q=yog


### Update food
PATCH http://localhost:3000/api/foods/1
content-type: application/json

{
    "calories": 100
}

### Delete food
DELETE  http://localhost:3000/api/foods/1
content-type: application/json


### Create a new user
POST http://localhost:3000/api/auth/register
content-type: application/json

{
    "name": "Test User",
    "email": "test@user.com",
    "username": "testuser",
    "password": "password1234"
}

### Login user
POST http://localhost:3000/api/auth/login
content-type: application/json

{
    "username": "testuser",
    "password": "password1234"
}

### Check user
GET http://localhost:3000/api/auth/whoami
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY0MjYyNTMwNywiZXhwIjoxNjQ1MjE3MzA3fQ.TFF57jmkL0Y_6wPpXXEum7Sbinl9z96F3ehDIQwav5A

### Get all recipes
GET http://localhost:3000/api/recipes

### Get a single recipe
GET http://localhost:3000/api/recipes/1

### Create a new recipe
POST http://localhost:3000/api/recipes
content-type: application/json

{ "recipe": {
    "name": "Test Turkey Meatballs",
    "description": "Yummy!",
    "servings": 24,
    "ingredients": [
        {
            "food": {
                "id": 4,
                "name": "egg",
                "brand": "generic",
                "isFood": true,
                "measures": [
                    {
                    "id": 4,
                    "label": "large",
                    "quantity": 1,
                    "calories": 72,
                    "carbs": 0,
                    "fat": 4,
                    "protein": 6
                    }
                ]
            },
            "measureId": 4,
            "quantity": 2,
            "notes": "beaten"
        },
        {
            "food":  {
                "id": 6,
                "name": "large flake oats",
                "brand": "Quaker",
                "isFood": true,
                "measures": [
                    {
                    "id": 6,
                    "label": "cup",
                    "quantity": 1,
                    "calories": 330,
                    "carbs": 60,
                    "fat": 6,
                    "protein": 12
                    },
                    {
                    "id": 7,
                    "label": "grams",
                    "quantity": 30,
                    "calories": 110,
                    "carbs": 20,
                    "fat": 2,
                    "protein": 4
                    }
                ]
            },
            "measureId": 6,
            "quantity": 1.5,
            "notes": ""
        },
        {
            "food": {
                "id": 5,
                "name": "turkey, ground",
                "brand": "generic",
                "isFood": true,
                "measures": [
                    {
                    "id": 5,
                    "label": "grams",
                    "quantity": 100,
                    "calories": 203,
                    "carbs": 0,
                    "fat": 10,
                    "protein": 27
                    }
                ]
            },
            "measureId": 5,
            "quantity": 900,
            "notes": ""
        }
    ],
    "steps": [
        {
            "order": 1,
            "instruction": "Mix all ingredients."
        },
        {
            "order": 2,
            "instruction": "Pour into pan."
        },
        {
            "order": 3,
            "instruction": "Bake."
        }
    ]
}
}